checkpoint_path: 'planners/giga/checkpoints/giga_pile.pt'
# checkpoint_path: 'planners/giga/checkpoints/giga_packed.pt'

# TODO: just remove this?
occ_thresh: 0.3
# TODO: if this is always set to false, remove it?
use_gaussian_filter: False
gaussian_filter_sigma: 1.0

min_width: 0.001
max_width: 0.080

low_qual_thresh: 0.6

nms_max_filter_size: 4

grasp_offset_dist: 0.05

# TODO: would this be useful?? if so, use it
debug_vis: False


up_dot_th: 0.5
gripper_z_th: 0.001
