PC:
  bb_center: [0.0, 0.0, 0.2]
  bb_dims: [0.7, 0.6, 0.42]

  crop_tight: true
  bb_dims_no_table: [0.7, 0.6, 0.35]
  bb_offset: 0.1

  voxel_size_ds: 0.004

EVAL:
  apply_geom_mask: true
  up_dot_th: 0.1
  gripper_z_th: 0.001
  num_grasps_return: 100

  allow_zero_margin: 0
  bin_vals: max
  extra_opening: 0.005
  filter_thres: 0.0001
  num_grasps_sample: 200
  max_farthest_points: 50
  first_thres: 0.2
  second_thres: 0.0
  with_replacement: false

DATA:
  checkpoint_path: planners/contact_graspnet/checkpoints/model.pt
  gripper_width: 0.08
  input_normals: false
  labels:
    bin_weights:
    - 0.16652107
    - 0.21488856
    - 0.37031708
    - 0.55618503
    - 0.75124664
    - 0.93943357
    - 1.07824539
    - 1.19423112
    - 1.55731375
    - 3.17161779
    offset_bins:
    - 0
    - 0.00794435329
    - 0.0158887021
    - 0.0238330509
    - 0.0317773996
    - 0.0397217484
    - 0.0476660972
    - 0.055610446
    - 0.0635547948
    - 0.0714991435
    - 0.08
  ndataset_points: 20000
  num_point: 2048
  num_input_points: 20000
  use_farthest_point: false # is this always false?


MODEL:
  asymmetric_model: true
  bin_offsets: true
  dir_vec_length_offset: false
  grasp_conf_head:
    conv1d: 1
    dropout_keep: 0.5
  grasp_dir_head:
    conv1d: 3
    dropout_keep: 0.7
  joint_head:
    conv1d: 4
    dropout_keep: 0.7
  joint_heads: false
  model: contact_graspnet
  pointnet_fp_modules:
  - mlp:
    - 256
    - 256
  - mlp:
    - 256
    - 128
  - mlp:
    - 128
    - 128
    - 128
  pointnet_sa_module:
    group_all: true
    mlp:
    - 256
    - 512
    - 1024
  pointnet_sa_modules_msg:
  - mlp_list:
    - - 32
      - 32
      - 64
    - - 64
      - 64
      - 128
    - - 64
      - 96
      - 128
    npoint: 2048
    nsample_list:
    - 32
    - 64
    - 128
    radius_list:
    - 0.02
    - 0.04
    - 0.08
  - mlp_list:
    - - 64
      - 64
      - 128
    - - 128
      - 128
      - 256
    - - 128
      - 128
      - 256
    npoint: 512
    nsample_list:
    - 64
    - 64
    - 128
    radius_list:
    - 0.04
    - 0.08
    - 0.16
  - mlp_list:
    - - 64
      - 64
      - 128
    - - 128
      - 128
      - 256
    - - 128
      - 128
      - 256
    npoint: 128
    nsample_list:
    - 64
    - 64
    - 128
    radius_list:
    - 0.08
    - 0.16
    - 0.32
  pred_contact_approach: false
  pred_contact_base: false
  pred_contact_offset: true
  pred_contact_success: true
  pred_grasps_adds: true
  pred_grasps_adds_gt2pred: false
