DATA:
  checkpoint_dir: planners/edge_grasp/checkpoints/
  checkpoint_iter: 180
MODEL:
  position_emd: True
  sample_num: 128
  learning_rate: 1.0e-5
EVAL:
  up_dot_th: 0.3
  rel_norm_min: 0.005
  rel_norm_max: 0.035
  depth_proj_min: 0.005
  depth_proj_max: 0.035
  check_gripper_collisions: False
  gripper_z_th: 0.005
  max_edges: 1000
  selection_th: 0.2
  max_grasps: 100








