checkpoint_path: 'planners/graspness/checkpoints/minkuresunet_realsense.tar'

bb_center: [0.0, 0.0, 0.2]
bb_dims: [0.7, 0.6, 0.38]
voxel_size_ds: 0.004

# collision detection between gripper and point cloud
collision_thresh: 0.01
voxel_size_cd: 0.005
approach_dist: 0.05

num_grasp_limit: 100

gripper_offset_dist: 0.05

apply_geom_mask: true

up_dot_th: 0.1
gripper_z_th: 0.001


# from pred_decode function?
# from other utils functions?
# should these be here? would need to move utils functions to main file
# GRASP_MAX_WIDTH: 0.1
# GRASPNESS_THRESHOLD: 0.1
# NUM_VIEW: 300
# NUM_ANGLE: 12
# NUM_DEPTH: 4
# M_POINT: 1024